export enum AmenityCategories {
  ACCESSIBILITY = "accessibility",
  ACCESSIBLE_PARKING = "accessible_parking",
  ACCESSIBLE_WHEELCHAIR = "accessible_wheelchair",
  AIR_CONDITIONING = "air_conditioning",
  AIRPORT_TRANSFER = "airport_transfer",
  BAR = "bar",
  CASINO = "casino",
  CRIB = "crib",
  DRY_CLEANING_LAUNDRY = "dry_cleaning_laundry",
  DRYER = "dryer",
  FREE_AIRPORT_TRANSFER = "free_airport_transfer",
  FREE_BREAKFAST = "free_breakfast",
  FREE_WIFI = "free_wifi",
  GYM = "gym",
  KITCHEN = "kitchen",
  MEETING_FACILITY = "meeting_facility",
  OCEAN_VIEW = "ocean_view",
  PARKING = "parking",
  PETS_ALLOWED = "pets_allowed",
  RESTAURANT_IN_HOTEL = "restaurant_in_hotel",
  SPA_SERVICES = "spa_services",
  SWIMMING_POOL = "swimming_pool",
  WASHER = "washer",
  WIFI = "wifi",
  OTHER = "other"
}